Repository LainForge/Neura-Launch-Dashboard, pull requests merged in 2023-10, with the labels that each got.

#18 ci: Add CI in GitHub Actions
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/ci-client.yml
  .github/workflows/ci-dashboard.yml
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted

#20 feat: added project routes
  dashboard/controllers/filesController.go
  dashboard/controllers/projectController.go
  dashboard/helpers/helpers.go
  dashboard/initializers/syncDB.go
  dashboard/main.go
  dashboard/models/project.go
Labels: enhancement

#26 Adds auto reload functionality to client dev container
  .docker/dev/client.dev.Dockerfile
  .github/workflows/ci-client.yml
  client/.gitignore
  client/pnpm-lock.yaml
  client/src/pages/Dashboard.tsx
  docker-compose.dev.yaml
Labels: hacktoberfest, hacktoberfest-accepted

#28 feat: Logging Implementation Issue
  CONTRIBUTING.md
  README.md
  builder/controllers/verifyCheckSumController.go
  dashboard/controllers/filesController.go
  dashboard/controllers/pingController.go
  dashboard/go.mod
  dashboard/go.sum
  dashboard/helpers/helpers.go
  dashboard/initializers/Logging.go
  dashboard/initializers/loadDB.go
  dashboard/main.go
  dashboard/middlewares/loggingMiddleware.go
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
